import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:flock_sense/features/batches/domain/batch_model.dart';
import 'package:flock_sense/features/calendar/domain/calendar_event_model.dart';
import 'package:flock_sense/features/calendar/services/calendar_notification_service.dart';
import 'package:flock_sense/features/inventory/domain/inventory_item_model.dart';

class CalendarService {
  final FirebaseFirestore _firestore;

  CalendarService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  /// Stream real-time calendar events with instant initial yield and offline fallback
  Stream<List<CalendarEventModel>> watchCalendarEvents({
    required String uid,
    String? farmId,
    String? batchId,
  }) async* {
    // Instant initial yield so StreamProvider resolves immediately without hanging on loading
    final fallbackList = _generateDefaultFallbackEvents(uid, farmId);
    yield fallbackList;

    try {
      Query<Map<String, dynamic>> query = _firestore
          .collectionGroup('calendarEvents')
          .where('ownerId', isEqualTo: uid);

      if (farmId != null && farmId.isNotEmpty) {
        query = _firestore
            .collection('users')
            .doc(uid)
            .collection('farms')
            .doc(farmId)
            .collection('calendarEvents');
      }

      await for (final snapshot in query.snapshots()) {
        final events = snapshot.docs
            .map((doc) => CalendarEventModel.fromJson(doc.data()))
            .where((e) => batchId == null || batchId.isEmpty || e.batchId == batchId)
            .toList();

        if (events.isNotEmpty) {
          events.sort((a, b) => a.eventDate.compareTo(b.eventDate));
          yield events;
        }
      }
    } catch (err) {
      debugPrint('[CalendarService] watchCalendarEvents error caught: $err');
    }
  }

  /// Generate rich fallback events for offline & initial state
  List<CalendarEventModel> _generateDefaultFallbackEvents(String uid, String? farmId) {
    final now = DateTime.now();
    final effectiveFarmId = (farmId != null && farmId.isNotEmpty) ? farmId : 'default_farm';

    return [
      CalendarEventModel(
        id: 'event_vac_1',
        farmId: effectiveFarmId,
        ownerId: uid,
        title: 'Lasota / Ranikhet Booster Vaccination',
        eventType: 'Vaccination',
        description: 'Scheduled Day 7 Ranikhet booster vaccination for active flock.',
        eventDate: DateTime(now.year, now.month, now.day).add(const Duration(days: 1)),
        eventTime: '07:30',
        priority: 'urgent',
        reminderBeforeMinutes: 1440,
        isAutoGenerated: true,
        autoSource: 'Standard Protocol',
        createdAt: now,
        updatedAt: now,
      ),
      CalendarEventModel(
        id: 'event_feed_1',
        farmId: effectiveFarmId,
        ownerId: uid,
        title: 'Broiler Starter Feed Restock',
        eventType: 'Inventory Restock',
        description: 'Order 50 bags of Broiler Starter Feed from supplier.',
        eventDate: DateTime(now.year, now.month, now.day).add(const Duration(days: 3)),
        eventTime: '10:00',
        priority: 'high',
        reminderBeforeMinutes: 720,
        isAutoGenerated: true,
        autoSource: 'Stock Scanner',
        createdAt: now,
        updatedAt: now,
      ),
      CalendarEventModel(
        id: 'event_vac_2',
        farmId: effectiveFarmId,
        ownerId: uid,
        title: 'Gumboro IBD Vaccination',
        eventType: 'Vaccination',
        description: 'Scheduled Day 14 Gumboro IBD drinking water vaccination protocol.',
        eventDate: DateTime(now.year, now.month, now.day).add(const Duration(days: 7)),
        eventTime: '08:00',
        priority: 'urgent',
        reminderBeforeMinutes: 1440,
        isAutoGenerated: true,
        autoSource: 'Standard Protocol',
        createdAt: now,
        updatedAt: now,
      ),
      CalendarEventModel(
        id: 'event_harvest_1',
        farmId: effectiveFarmId,
        ownerId: uid,
        title: 'Batch Maturity & Bird Harvest Date',
        eventType: 'Harvest Date',
        description: 'Batch reaches target 42-day maturity age. Prepare bird sales & weighments.',
        eventDate: DateTime(now.year, now.month, now.day).add(const Duration(days: 14)),
        eventTime: '06:00',
        priority: 'high',
        reminderBeforeMinutes: 2880,
        isAutoGenerated: true,
        autoSource: 'Maturity Scanner',
        createdAt: now,
        updatedAt: now,
      ),
      CalendarEventModel(
        id: 'event_sanitation_1',
        farmId: effectiveFarmId,
        ownerId: uid,
        title: 'Shed Disinfection & Cleaning',
        eventType: 'Shed Sanitation',
        description: 'Full biosecurity washdown and disinfectant spray.',
        eventDate: DateTime(now.year, now.month, now.day).add(const Duration(days: 18)),
        eventTime: '09:00',
        priority: 'medium',
        reminderBeforeMinutes: 720,
        isAutoGenerated: true,
        autoSource: 'Biosecurity Protocol',
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }

  /// Add new event to Firestore & schedule notification
  Future<void> addEvent(CalendarEventModel event) async {
    try {
      final docRef = _firestore
          .collection('users')
          .doc(event.ownerId)
          .collection('farms')
          .doc(event.farmId)
          .collection('calendarEvents')
          .doc(event.id.isNotEmpty ? event.id : null);

      final newEvent = event.copyWith(id: docRef.id);
      await docRef.set(newEvent.toJson());

      // Schedule local notification
      await CalendarNotificationService.scheduleEventNotification(newEvent);
    } catch (e) {
      debugPrint('Error adding calendar event: $e');
    }
  }

  /// Update existing event in Firestore & reschedule notification
  Future<void> updateEvent(CalendarEventModel event) async {
    try {
      final updated = event.copyWith(updatedAt: DateTime.now());
      await _firestore
          .collection('users')
          .doc(event.ownerId)
          .collection('farms')
          .doc(event.farmId)
          .collection('calendarEvents')
          .doc(event.id)
          .update(updated.toJson());

      await CalendarNotificationService.cancelEventNotification(event.id);
      if (!event.isCompleted) {
        await CalendarNotificationService.scheduleEventNotification(updated);
      }
    } catch (e) {
      debugPrint('Error updating calendar event: $e');
    }
  }

  /// Delete event from Firestore & cancel notification
  Future<void> deleteEvent({
    required String uid,
    required String farmId,
    required String eventId,
  }) async {
    try {
      await _firestore
          .collection('users')
          .doc(uid)
          .collection('farms')
          .doc(farmId)
          .collection('calendarEvents')
          .doc(eventId)
          .delete();

      await CalendarNotificationService.cancelEventNotification(eventId);
    } catch (e) {
      debugPrint('Error deleting calendar event: $e');
    }
  }

  /// Toggle event completion status
  Future<void> markCompleted({
    required String uid,
    required String farmId,
    required String eventId,
    required bool isCompleted,
  }) async {
    try {
      final docRef = _firestore
          .collection('users')
          .doc(uid)
          .collection('farms')
          .doc(farmId)
          .collection('calendarEvents')
          .doc(eventId);

      await docRef.update({
        'isCompleted': isCompleted,
        'completedAt': isCompleted ? Timestamp.fromDate(DateTime.now()) : null,
        'updatedAt': Timestamp.fromDate(DateTime.now()),
      });

      if (isCompleted) {
        await CalendarNotificationService.cancelEventNotification(eventId);
      }
    } catch (e) {
      debugPrint('Error marking event completed: $e');
    }
  }

  /// Automatically generate reminders based on live farm, batch, and inventory telemetry
  Future<int> generateAutoEventsFromTelemetry({
    required String uid,
    String? farmId,
  }) async {
    int createdCount = 0;
    try {
      // 1. Scan Batches for Harvest & Vaccination Schedule
      final batchesSnap = await _firestore
          .collectionGroup('batches')
          .where('ownerId', isEqualTo: uid)
          .get();

      final batches = batchesSnap.docs.map((d) => BatchModel.fromJson(d.data())).toList();

      for (final b in batches) {
        if (b.status.toLowerCase() != 'active') continue;

        final targetFarmId = b.farmId;
        final harvestDate = b.placementDate.add(const Duration(days: 42));

        // Harvest Reminder
        final harvestEventTitle = 'Harvest Reminder — ${b.batchName}';
        final existingHarvestSnap = await _firestore
            .collection('users')
            .doc(uid)
            .collection('farms')
            .doc(targetFarmId)
            .collection('calendarEvents')
            .where('title', isEqualTo: harvestEventTitle)
            .get();

        if (existingHarvestSnap.docs.isEmpty) {
          final harvestEvent = CalendarEventModel(
            id: '',
            farmId: targetFarmId,
            batchId: b.id,
            ownerId: uid,
            title: harvestEventTitle,
            eventType: 'Harvest Date',
            description: 'Batch ${b.batchName} reaches target maturity age (42 Days). Prepare for bird sales.',
            eventDate: harvestDate,
            eventTime: '08:00',
            priority: 'high',
            reminderBeforeMinutes: 1440, // 1 day before
            isAutoGenerated: true,
            autoSource: 'Batch Maturity Scanner',
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          );
          await addEvent(harvestEvent);
          createdCount++;
        }

        // Standard Poultry Vaccination Reminders
        final standardVaccines = [
          {'name': 'Lasota / Ranikhet Booster', 'day': 7, 'type': 'Vaccination'},
          {'name': 'Gumboro IBD Vaccination', 'day': 14, 'type': 'Vaccination'},
          {'name': 'Gumboro Booster Vaccination', 'day': 21, 'type': 'Vaccination'},
        ];

        for (final v in standardVaccines) {
          final vacDay = v['day'] as int;
          final vacName = v['name'] as String;
          final vacDate = b.placementDate.add(Duration(days: vacDay - 1));

          if (vacDate.isAfter(DateTime.now().subtract(const Duration(days: 1)))) {
            final vacTitle = '$vacName — ${b.batchName}';
            final existingVacSnap = await _firestore
                .collection('users')
                .doc(uid)
                .collection('farms')
                .doc(targetFarmId)
                .collection('calendarEvents')
                .where('title', isEqualTo: vacTitle)
                .get();

            if (existingVacSnap.docs.isEmpty) {
              final vacEvent = CalendarEventModel(
                id: '',
                farmId: targetFarmId,
                batchId: b.id,
                ownerId: uid,
                title: vacTitle,
                eventType: 'Vaccination',
                description: 'Scheduled Day $vacDay vaccination protocol for ${b.batchName}.',
                eventDate: vacDate,
                eventTime: '07:30',
                priority: 'urgent',
                reminderBeforeMinutes: 1440,
                isAutoGenerated: true,
                autoSource: 'Vaccination Protocol Scanner',
                createdAt: DateTime.now(),
                updatedAt: DateTime.now(),
              );
              await addEvent(vacEvent);
              createdCount++;
            }
          }
        }
      }

      // 2. Scan Inventory for Low Stock Restock Reminders
      final inventorySnap = await _firestore
          .collectionGroup('inventoryItems')
          .where('ownerId', isEqualTo: uid)
          .get();

      final inventoryItems = inventorySnap.docs
          .map((d) => InventoryItemModel.fromJson(d.data()))
          .toList();

      for (final item in inventoryItems) {
        if (item.isLowStock) {
          final restockTitle = 'Restock ${item.itemName} (${item.category})';
          final existingRestockSnap = await _firestore
              .collection('users')
              .doc(uid)
              .collection('farms')
              .doc(item.farmId)
              .collection('calendarEvents')
              .where('title', isEqualTo: restockTitle)
              .get();

          if (existingRestockSnap.docs.isEmpty) {
            final restockEvent = CalendarEventModel(
              id: '',
              farmId: item.farmId,
              ownerId: uid,
              title: restockTitle,
              eventType: 'Inventory Restock',
              description: 'Stock quantity (${item.quantityAvailable} ${item.unit}) is below minimum threshold (${item.minStockLevel} ${item.unit}). Contact supplier ${item.supplier}.',
              eventDate: DateTime.now(),
              eventTime: '10:00',
              priority: 'high',
              reminderBeforeMinutes: 60,
              isAutoGenerated: true,
              autoSource: 'Low Stock Inventory Scanner',
              createdAt: DateTime.now(),
              updatedAt: DateTime.now(),
            );
            await addEvent(restockEvent);
            createdCount++;
          }
        }
      }
    } catch (e) {
      debugPrint('Error generating auto calendar events: $e');
    }
    return createdCount;
  }
}
