import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:flock_sense/core/theme/app_colors.dart';
import 'package:flock_sense/core/widgets/app_bottom_sheet.dart';
import 'package:flock_sense/core/widgets/app_button.dart';
import 'package:flock_sense/core/widgets/app_dialog.dart';
import 'package:flock_sense/features/calendar/domain/calendar_event_model.dart';
import 'package:flock_sense/features/calendar/presentation/providers/calendar_providers.dart';
import 'package:flock_sense/features/calendar/presentation/screens/calendar_event_form_screen.dart';

class EventDetailsSheet extends ConsumerWidget {
  const EventDetailsSheet({super.key, required this.event});

  final CalendarEventModel event;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final dateFormat = DateFormat('EEEE, MMM dd, yyyy');
    final theme = Theme.of(context);

    return AppBottomSheet(
      title: event.title,
      subtitle: event.description,
      showCloseButton: true,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: event.color.withOpacity(0.12),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  event.eventType,
                  style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: event.color),
                ),
              ),
              const SizedBox(width: 8),
              if (event.isOverdue)
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(color: AppColors.danger, borderRadius: BorderRadius.circular(6)),
                  child: const Text('OVERDUE', style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.white)),
                ),
              const Spacer(),
              IconButton(
                icon: const Icon(Icons.edit_outlined),
                onPressed: () {
                  Navigator.pop(context);
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => CalendarEventFormScreen(existingEvent: event),
                    ),
                  );
                },
              ),
              IconButton(
                icon: const Icon(Icons.delete_outline, color: AppColors.danger),
                onPressed: () => _confirmDelete(context, ref),
              ),
            ],
          ),
          const SizedBox(height: 14),

          _row(Icons.event_outlined, 'Date', dateFormat.format(event.eventDate), theme),
          _row(Icons.access_time_rounded, 'Time', event.eventTime, theme),
          _row(Icons.notifications_active_outlined, 'Reminder Before', '${event.reminderBeforeMinutes} minutes', theme),
          _row(Icons.flag_outlined, 'Priority', event.priority.toUpperCase(), theme),
          _row(Icons.repeat, 'Repeat', event.repeat.toUpperCase(), theme),
          if (event.isAutoGenerated)
            _row(Icons.smart_toy_outlined, 'Auto Scanner', event.autoSource ?? 'Telemetry Engine', theme),
          if (event.notes != null && event.notes!.isNotEmpty)
            _row(Icons.notes, 'Notes', event.notes!, theme),

          const SizedBox(height: 24),

          AppButton(
            label: event.isCompleted ? 'Mark as Pending' : 'Mark as Completed',
            icon: event.isCompleted ? Icons.undo : Icons.check_circle_outline,
            onPressed: () async {
              final service = ref.read(calendarServiceProvider);
              await service.markCompleted(
                uid: event.ownerId,
                farmId: event.farmId,
                eventId: event.id,
                isCompleted: !event.isCompleted,
              );
              if (context.mounted) {
                Navigator.pop(context);
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      event.isCompleted
                          ? 'Event marked as pending.'
                          : 'Event marked as completed! 🎉',
                    ),
                    backgroundColor: AppColors.primary,
                  ),
                );
              }
            },
            variant: event.isCompleted ? AppButtonVariant.secondary : AppButtonVariant.primary,
            width: double.infinity,
          ),
        ],
      ),
    );
  }

  Widget _row(IconData icon, String label, String value, ThemeData theme) {
    final isDark = theme.brightness == Brightness.dark;
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        children: [
          Icon(icon, size: 16, color: isDark ? AppColors.darkTextSecondary : AppColors.textSecondary),
          const SizedBox(width: 8),
          Text('$label: ', style: theme.textTheme.bodySmall),
          Expanded(
            child: Text(
              value,
              style: theme.textTheme.titleSmall?.copyWith(
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _confirmDelete(BuildContext context, WidgetRef ref) async {
    final confirm = await AppDialog.confirm(
      context: context,
      title: 'Delete Event?',
      message: 'Are you sure you want to delete "${event.title}"?',
      confirmLabel: 'Delete',
      isDanger: true,
    );

    if (confirm) {
      try {
        final service = ref.read(calendarServiceProvider);
        await service.deleteEvent(
          uid: event.ownerId,
          farmId: event.farmId,
          eventId: event.id,
        );

        if (context.mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('"${event.title}" deleted.'),
              backgroundColor: AppColors.primary,
            ),
          );
        }
      } catch (e) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to delete event: $e'),
              backgroundColor: AppColors.danger,
            ),
          );
        }
      }
    }
  }
}

