// File generated by FlutterFire CLI & configured for flocksense-76430
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-QSt3jacb6SyI31uaZMs8uXqLeyRHOs',
    appId: '1:130535887202:web:39a109313bf441a1ea9c3b',
    messagingSenderId: '130535887202',
    projectId: 'flocksense-76430',
    authDomain: 'flocksense-76430.firebaseapp.com',
    storageBucket: 'flocksense-76430.firebasestorage.app',
    measurementId: 'G-LLK7495ZCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU-QSt3jacb6SyI31uaZMs8uXqLeyRHOs',
    appId: '1:130535887202:web:39a109313bf441a1ea9c3b',
    messagingSenderId: '130535887202',
    projectId: 'flocksense-76430',
    authDomain: 'flocksense-76430.firebaseapp.com',
    storageBucket: 'flocksense-76430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-QSt3jacb6SyI31uaZMs8uXqLeyRHOs',
    appId: '1:130535887202:web:39a109313bf441a1ea9c3b',
    messagingSenderId: '130535887202',
    projectId: 'flocksense-76430',
    storageBucket: 'flocksense-76430.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-QSt3jacb6SyI31uaZMs8uXqLeyRHOs',
    appId: '1:130535887202:web:39a109313bf441a1ea9c3b',
    messagingSenderId: '130535887202',
    projectId: 'flocksense-76430',
    storageBucket: 'flocksense-76430.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-QSt3jacb6SyI31uaZMs8uXqLeyRHOs',
    appId: '1:130535887202:web:39a109313bf441a1ea9c3b',
    messagingSenderId: '130535887202',
    projectId: 'flocksense-76430',
    authDomain: 'flocksense-76430.firebaseapp.com',
    storageBucket: 'flocksense-76430.firebasestorage.app',
    measurementId: 'G-LLK7495ZCK',
  );
}
