import 'package:flutter/material.dart';
import 'package:flock_sense/core/theme/app_colors.dart';
import 'package:flock_sense/core/theme/app_design.dart';
import 'package:flock_sense/core/theme/app_typography.dart';
import 'package:flock_sense/core/widgets/app_button.dart';
import 'package:flock_sense/core/widgets/app_card.dart';
import 'package:flock_sense/core/widgets/status_badge.dart';
import 'package:flock_sense/features/intelligence/domain/role_recommendation_model.dart';

/// Unified Role Recommendations Widget (Part 10 & 14)
/// Displays WHAT?, WHY?, PRIORITY?, WHO?, SOURCE?, STATUS? with interactive status management
class RoleRecommendationsWidget extends StatefulWidget {
  final List<RoleRecommendationModel> recommendations;
  final Function(RoleRecommendationModel rec, RecommendationStatus newStatus)? onStatusChanged;

  const RoleRecommendationsWidget({
    super.key,
    required this.recommendations,
    this.onStatusChanged,
  });

  @override
  State<RoleRecommendationsWidget> createState() => _RoleRecommendationsWidgetState();
}

class _RoleRecommendationsWidgetState extends State<RoleRecommendationsWidget> {
  late Map<String, RecommendationStatus> _localStatuses;

  @override
  void initState() {
    super.initState();
    _localStatuses = {for (var r in widget.recommendations) r.id: r.status};
  }

  @override
  void didUpdateWidget(covariant RoleRecommendationsWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    for (var r in widget.recommendations) {
      if (!_localStatuses.containsKey(r.id)) {
        _localStatuses[r.id] = r.status;
      }
    }
  }

  void _updateStatus(RoleRecommendationModel rec, RecommendationStatus newStatus) {
    setState(() {
      _localStatuses[rec.id] = newStatus;
    });
    widget.onStatusChanged?.call(rec, newStatus);
  }

  @override
  Widget build(BuildContext context) {
    if (widget.recommendations.isEmpty) {
      return AppCard(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 16),
          child: Center(
            child: Text('All biosecurity & health recommendations completed or clear.',
                style: AppTypography.bodySmall),
          ),
        ),
      );
    }

    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: AppColors.primaryLight,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Icon(Icons.checklist_rtl_rounded, color: AppColors.primary, size: 20),
                  ),
                  const SizedBox(width: 10),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Actionable Decision Recommendations', style: AppTypography.headingSmall),
                      Text('Transparent operational guidance generated by Intelligence Engine', style: AppTypography.bodySmall),
                    ],
                  ),
                ],
              ),
              StatusBadge(
                label: '${widget.recommendations.length} Actions',
                type: StatusBadgeType.primary,
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Cards list
          ListView.separated(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: widget.recommendations.length,
            separatorBuilder: (_, __) => const SizedBox(height: 12),
            itemBuilder: (context, index) {
              final rec = widget.recommendations[index];
              final currentStatus = _localStatuses[rec.id] ?? rec.status;
              return _buildRecommendationCard(rec, currentStatus);
            },
          ),
        ],
      ),
    );
  }

  Widget _buildRecommendationCard(RoleRecommendationModel rec, RecommendationStatus currentStatus) {
    final isCritical = rec.priority == RecommendationPriority.critical;
    final isHigh = rec.priority == RecommendationPriority.high;

    Color priorityColor = AppColors.info;
    if (isCritical) {
      priorityColor = AppColors.critical;
    } else if (isHigh) {
      priorityColor = AppColors.warning;
    }

    final isDone = currentStatus == RecommendationStatus.completed;

    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: isDone ? AppColors.surfaceSubtle : AppColors.surface,
        borderRadius: BorderRadius.circular(AppDesign.radiusSm),
        border: Border.all(
          color: isDone ? AppColors.border : (isCritical ? AppColors.critical.withOpacity(0.4) : AppColors.border),
          width: isCritical ? 1.5 : 1.0,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Top Row: Title + Priority + Status Badge
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                      decoration: BoxDecoration(
                        color: priorityColor.withOpacity(0.12),
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: Text(
                        rec.priority.label,
                        style: TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.w700,
                          color: priorityColor,
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        rec.title,
                        style: AppTypography.labelMedium.copyWith(
                          fontWeight: FontWeight.w700,
                          decoration: isDone ? TextDecoration.lineThrough : null,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
              ),
              StatusBadge(
                label: currentStatus.label,
                type: isDone
                    ? StatusBadgeType.healthy
                    : (currentStatus == RecommendationStatus.in_progress
                        ? StatusBadgeType.warning
                        : StatusBadgeType.info),
              ),
            ],
          ),
          const SizedBox(height: 8),

          // WHAT? Action
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('WHAT: ', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12, color: AppColors.slate700)),
              Expanded(
                child: Text(rec.action, style: AppTypography.bodySmall.copyWith(color: AppColors.slate900)),
              ),
            ],
          ),
          const SizedBox(height: 4),

          // WHY? Reason
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('WHY: ', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12, color: AppColors.slate600)),
              Expanded(
                child: Text(rec.reason, style: AppTypography.caption.copyWith(color: AppColors.slate700)),
              ),
            ],
          ),
          const SizedBox(height: 8),

          // Footer: SOURCE + RESPONSIBLE + Action Buttons
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Text(
                  'Source: ${rec.source} • Resp: ${rec.responsibleRole.label}',
                  style: AppTypography.caption.copyWith(color: AppColors.slate500, fontSize: 11),
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (currentStatus == RecommendationStatus.recommended)
                    AppButton(
                      label: 'Acknowledge',
                      size: AppButtonSize.small,
                      variant: AppButtonVariant.secondary,
                      onPressed: () => _updateStatus(rec, RecommendationStatus.acknowledged),
                    ),
                  if (currentStatus == RecommendationStatus.acknowledged || currentStatus == RecommendationStatus.recommended) ...[
                    const SizedBox(width: 6),
                    AppButton(
                      label: 'Start Action',
                      size: AppButtonSize.small,
                      variant: AppButtonVariant.secondary,
                      onPressed: () => _updateStatus(rec, RecommendationStatus.in_progress),
                    ),
                  ],
                  if (currentStatus == RecommendationStatus.in_progress) ...[
                    const SizedBox(width: 6),
                    AppButton(
                      label: 'Mark Complete',
                      size: AppButtonSize.small,
                      variant: AppButtonVariant.primary,
                      onPressed: () => _updateStatus(rec, RecommendationStatus.completed),
                    ),
                  ],
                  if (isDone)
                    Text('Done', style: AppTypography.caption.copyWith(color: AppColors.healthy, fontWeight: FontWeight.w700)),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }
}
