import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class CalendarEventModel {
  final String id;
  final String farmId;
  final String? batchId;
  final String ownerId;
  final String title;
  final String eventType; // 'Vaccination', 'Medicine', 'Feed Delivery', 'Water Check', 'Cleaning Schedule', 'Bird Weighing', 'Batch Placement', 'Harvest Date', 'Inventory Restock', 'Custom Reminder'
  final String? description;
  final DateTime eventDate;
  final String eventTime; // e.g. '09:00'
  final String repeat; // 'none', 'daily', 'weekly', 'monthly'
  final String priority; // 'low', 'medium', 'high', 'urgent'
  final int reminderBeforeMinutes; // 15, 30, 60, 360, 1440, 4320, 10080
  final bool isCompleted;
  final DateTime? completedAt;
  final bool isAutoGenerated;
  final String? autoSource;
  final String? notes;
  final DateTime createdAt;
  final DateTime updatedAt;

  const CalendarEventModel({
    required this.id,
    required this.farmId,
    this.batchId,
    required this.ownerId,
    required this.title,
    required this.eventType,
    this.description,
    required this.eventDate,
    required this.eventTime,
    this.repeat = 'none',
    this.priority = 'medium',
    this.reminderBeforeMinutes = 30,
    this.isCompleted = false,
    this.completedAt,
    this.isAutoGenerated = false,
    this.autoSource,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Event color mapping
  Color get color {
    switch (eventType.toLowerCase()) {
      case 'vaccination':
        return const Color(0xFF1E88E5); // Blue
      case 'medicine':
        return const Color(0xFF43A047); // Green
      case 'harvest date':
      case 'harvest':
        return const Color(0xFFFB8C00); // Orange
      case 'cleaning schedule':
      case 'cleaning':
        return const Color(0xFF8E24AA); // Purple
      case 'inventory restock':
      case 'inventory':
        return const Color(0xFFE53935); // Red
      case 'feed delivery':
        return const Color(0xFFFFA000); // Amber
      case 'water check':
        return const Color(0xFF00ACC1); // Cyan
      case 'bird weighing':
        return const Color(0xFF00897B); // Teal
      case 'batch placement':
        return const Color(0xFF3949AB); // Indigo
      case 'custom reminder':
      default:
        return const Color(0xFF757575); // Grey
    }
  }

  /// Full DateTime combining eventDate and eventTime
  DateTime get fullDateTime {
    final parts = eventTime.split(':');
    final hour = parts.isNotEmpty ? (int.tryParse(parts[0]) ?? 9) : 9;
    final minute = parts.length > 1 ? (int.tryParse(parts[1]) ?? 0) : 0;
    return DateTime(eventDate.year, eventDate.month, eventDate.day, hour, minute);
  }

  bool get isOverdue {
    if (isCompleted) return false;
    final now = DateTime.now();
    return fullDateTime.isBefore(now);
  }

  bool get isToday {
    final now = DateTime.now();
    return eventDate.year == now.year && eventDate.month == now.month && eventDate.day == now.day;
  }

  bool get isUpcoming => !isCompleted && !isOverdue;

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'farmId': farmId,
      'batchId': batchId,
      'ownerId': ownerId,
      'title': title,
      'eventType': eventType,
      'description': description,
      'eventDate': Timestamp.fromDate(eventDate),
      'eventTime': eventTime,
      'repeat': repeat,
      'priority': priority,
      'reminderBeforeMinutes': reminderBeforeMinutes,
      'isCompleted': isCompleted,
      'completedAt': completedAt != null ? Timestamp.fromDate(completedAt!) : null,
      'isAutoGenerated': isAutoGenerated,
      'autoSource': autoSource,
      'notes': notes,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
    };
  }

  factory CalendarEventModel.fromJson(Map<String, dynamic> json) {
    DateTime parseDate(dynamic v) {
      if (v is Timestamp) return v.toDate();
      if (v is String && v.isNotEmpty) {
        return DateTime.tryParse(v) ?? DateTime.now();
      }
      return DateTime.now();
    }

    return CalendarEventModel(
      id: json['id'] as String? ?? '',
      farmId: json['farmId'] as String? ?? '',
      batchId: json['batchId'] as String?,
      ownerId: json['ownerId'] as String? ?? '',
      title: json['title'] as String? ?? 'Untitled Event',
      eventType: json['eventType'] as String? ?? 'Custom Reminder',
      description: json['description'] as String?,
      eventDate: parseDate(json['eventDate']),
      eventTime: json['eventTime'] as String? ?? '09:00',
      repeat: json['repeat'] as String? ?? 'none',
      priority: json['priority'] as String? ?? 'medium',
      reminderBeforeMinutes: json['reminderBeforeMinutes'] as int? ?? 30,
      isCompleted: json['isCompleted'] as bool? ?? false,
      completedAt: json['completedAt'] != null ? parseDate(json['completedAt']) : null,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      autoSource: json['autoSource'] as String?,
      notes: json['notes'] as String?,
      createdAt: parseDate(json['createdAt']),
      updatedAt: parseDate(json['updatedAt']),
    );
  }

  CalendarEventModel copyWith({
    String? id,
    String? farmId,
    String? batchId,
    String? ownerId,
    String? title,
    String? eventType,
    String? description,
    DateTime? eventDate,
    String? eventTime,
    String? repeat,
    String? priority,
    int? reminderBeforeMinutes,
    bool? isCompleted,
    DateTime? completedAt,
    bool? isAutoGenerated,
    String? autoSource,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return CalendarEventModel(
      id: id ?? this.id,
      farmId: farmId ?? this.farmId,
      batchId: batchId ?? this.batchId,
      ownerId: ownerId ?? this.ownerId,
      title: title ?? this.title,
      eventType: eventType ?? this.eventType,
      description: description ?? this.description,
      eventDate: eventDate ?? this.eventDate,
      eventTime: eventTime ?? this.eventTime,
      repeat: repeat ?? this.repeat,
      priority: priority ?? this.priority,
      reminderBeforeMinutes: reminderBeforeMinutes ?? this.reminderBeforeMinutes,
      isCompleted: isCompleted ?? this.isCompleted,
      completedAt: completedAt ?? this.completedAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      autoSource: autoSource ?? this.autoSource,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
